### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by lehurndonk** [ultimate-enable-right-click/ultimate-enable-right-click.github.io#1]
this site ok a few days ago
now not working
https://noblemtl.com/series/that-mans-101st-bad-ending/

**Comment by ultimate-enable-right-click** [comment]
You should activate the "Enable Text Selection (CSS)" component of the extension. Then you can select and copy texts just fine.

To do so, click on the extension's icon in the browser's toolbar to show the extension's popup menus, and then toggle the knob near the "Enable Text Selection (CSS)" label so that it becomes green.
